#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BLOCK_SIZE 1024
#define ERROR_FILE_IHANDLING -1
#define ERROR_FILE_SHANDLING NULL
#define LINE_FLAG_INDEX 0
#define WORD_FLAG_INDEX 1
#define CHAR_FLAG_INDEX 2
#define BYTE_FLAG_INDEX 3
#define LINE_FLAG 'l'
#define WORD_FLAG 'w'
#define CHAR_FLAG 'm'
#define BYTE_FLAG 'c'
#define LINE_FLAG_MASK 0x01  // 0001
#define WORD_FLAG_MASK 0x02  // 0010
#define CHAR_FLAG_MASK 0x04  // 0100
#define BYTE_FLAG_MASK 0x08  // 1000

#endif // CONSTANTS_H
